add a workaround for rabbitmq_vhost when running with --noop or --tags
This fixes the error:
Error: Could not prefetch rabbitmq_vhost provider 'rabbitmqctl': Command rabbitmqctl is missing

The problem, and the workaround, are the same as that described in
commit 8a3a27a0584666e71bf64b2eb49adf79133939c1, "add a workaround for
running with --noop or --tags".

This is necessary because the original workaround is for
rabbitmqctl_list(), whereas rabbitmq_version() calls rabbitmqctl()
directly.

Other callers of rabbitmq_version() should not need this workaround,
since they are not run in a state where rabbitmq itself is not yet
installed.