add a workaround for running with --noop or --tags
This fixes errors like:
Error: Could not prefetch rabbitmq_user provider 'rabbitmqctl': Command rabbitmqctl is missing

...under the following conditions:
* The client does not yet have rabbitmq installed.
* Puppet is run with --noop or a specific set of --tags that does not
  include rabbitmq resources.

On a fresh client in normal operation, the sequence of events is:
1. Install the rabbitmq package.
2. Start the service.
3. Run the prefetch for resources which use rabbitmqctl (e.g. rabbitmq_user).
4. Apply the resources (or not, if they already exist).

On a fresh client running with --noop or tags, the sequence of events is:
1. (nothing)
2. (nothing)
3. Run the prefetch, but fail.

To work around this, assume that if rabbitmq management commands are not
found, then rabbitmq is not installed at all, thus all corresponding
resources are not present.

On a normal run, the rabbitmq packages will be installed before
resources which need rabbitmq commands, so the workaround is never
triggered.

This is _probably_ not an ideal fix, but it's the best I have.